version: '3.8'

services:
  backend-project2:
    image: backend-project2:latest
    ports:
      - "8080:8080"  # Maps the container's port 8080 to the host's port 8080
    environment:
      - db_url=jdbc:mysql://c584md9egjnm02sk.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/v4hbf09hn2uv0gfc?useSSL=false&serverTimezone=UTC
      - db_username=f2vju459mp652zxw
      - db_password=imzbufv1tqr959eg
    restart: always  # Restarts the container automatically in case of failure
